# Generated by Django 2.2.9 on 2020-08-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200824_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка украсит ваш пост', null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
