# Generated by Django 2.2.6 on 2020-08-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200829_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка украсит ваш пост', null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
