# Generated by Django 2.2.6 on 2020-10-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20201017_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='title',
            field=models.CharField(default='категория', max_length=200, unique=True),
        ),
    ]
