# Generated by Django 2.2.6 on 2020-10-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20201017_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='title',
            field=models.CharField(help_text='Назовите категорию', max_length=200, unique=True),
        ),
    ]
