# Generated by Django 2.2.6 on 2020-10-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20201017_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroup',
            name='title',
        ),
    ]
