# Generated by Django 2.2.6 on 2020-10-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_remove_subgroup_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='title',
            field=models.CharField(default='gategory', help_text='Назовите категорию', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
