# Generated by Django 2.2.6 on 2020-10-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20201020_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(help_text='Выберите Группу', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='posts.Group', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Уникальное название связанное с заголовком. Используйте латинские буквы. Пробелы заменяйте "-"', max_length=25, unique=True, verbose_name='уникальное имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Назовите категорию', max_length=200, unique=True, verbose_name='Заголовок'),
        ),
    ]
