# Generated by Django 2.2.6 on 2020-10-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20201020_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_important',
            field=models.BooleanField(blank=True, help_text='Поставте галочку если хотите отметить это важным', null=True, verbose_name='Новость?'),
        ),
    ]
