# Generated by Django 2.2.6 on 2020-10-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_post_is_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Поставте галочку если хотите отметить это важным', verbose_name='Новость?'),
        ),
    ]
